/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteRecord = IDL.Record({
  'id' : IDL.Nat,
  'additionalNotes' : IDL.Text,
  'name' : IDL.Text,
  'referenceSheetUrl' : IDL.Opt(IDL.Text),
  'whatYouWantMade' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'budgetRange' : IDL.Text,
  'fursonaName' : IDL.Text,
});
export const QuoteRequest = IDL.Record({
  'additionalNotes' : IDL.Text,
  'name' : IDL.Text,
  'referenceSheetUrl' : IDL.Opt(IDL.Text),
  'whatYouWantMade' : IDL.Text,
  'email' : IDL.Text,
  'budgetRange' : IDL.Text,
  'fursonaName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getQuotes' : IDL.Func([], [IDL.Vec(QuoteRecord)], ['query']),
  'submitQuote' : IDL.Func(
      [QuoteRequest],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteRecord = IDL.Record({
    'id' : IDL.Nat,
    'additionalNotes' : IDL.Text,
    'name' : IDL.Text,
    'referenceSheetUrl' : IDL.Opt(IDL.Text),
    'whatYouWantMade' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'budgetRange' : IDL.Text,
    'fursonaName' : IDL.Text,
  });
  const QuoteRequest = IDL.Record({
    'additionalNotes' : IDL.Text,
    'name' : IDL.Text,
    'referenceSheetUrl' : IDL.Opt(IDL.Text),
    'whatYouWantMade' : IDL.Text,
    'email' : IDL.Text,
    'budgetRange' : IDL.Text,
    'fursonaName' : IDL.Text,
  });
  
  return IDL.Service({
    'getQuotes' : IDL.Func([], [IDL.Vec(QuoteRecord)], ['query']),
    'submitQuote' : IDL.Func(
        [QuoteRequest],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };