/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuoteRequest {
    additionalNotes: string;
    name: string;
    referenceSheetUrl?: string;
    whatYouWantMade: string;
    email: string;
    budgetRange: string;
    fursonaName: string;
}
export interface QuoteRecord {
    id: bigint;
    additionalNotes: string;
    name: string;
    referenceSheetUrl?: string;
    whatYouWantMade: string;
    submittedAt: bigint;
    email: string;
    budgetRange: string;
    fursonaName: string;
}
export interface backendInterface {
    getQuotes(): Promise<Array<QuoteRecord>>;
    submitQuote(req: QuoteRequest): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { QuoteRecord as _QuoteRecord, QuoteRequest as _QuoteRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getQuotes(): Promise<Array<QuoteRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotes();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotes();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuote(arg0: QuoteRequest): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(to_candid_QuoteRequest_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(to_candid_QuoteRequest_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_QuoteRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteRecord): QuoteRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    additionalNotes: string;
    name: string;
    referenceSheetUrl: [] | [string];
    whatYouWantMade: string;
    submittedAt: bigint;
    email: string;
    budgetRange: string;
    fursonaName: string;
}): {
    id: bigint;
    additionalNotes: string;
    name: string;
    referenceSheetUrl?: string;
    whatYouWantMade: string;
    submittedAt: bigint;
    email: string;
    budgetRange: string;
    fursonaName: string;
} {
    return {
        id: value.id,
        additionalNotes: value.additionalNotes,
        name: value.name,
        referenceSheetUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.referenceSheetUrl)),
        whatYouWantMade: value.whatYouWantMade,
        submittedAt: value.submittedAt,
        email: value.email,
        budgetRange: value.budgetRange,
        fursonaName: value.fursonaName
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuoteRecord>): Array<QuoteRecord> {
    return value.map((x)=>from_candid_QuoteRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_QuoteRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteRequest): _QuoteRequest {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    additionalNotes: string;
    name: string;
    referenceSheetUrl?: string;
    whatYouWantMade: string;
    email: string;
    budgetRange: string;
    fursonaName: string;
}): {
    additionalNotes: string;
    name: string;
    referenceSheetUrl: [] | [string];
    whatYouWantMade: string;
    email: string;
    budgetRange: string;
    fursonaName: string;
} {
    return {
        additionalNotes: value.additionalNotes,
        name: value.name,
        referenceSheetUrl: value.referenceSheetUrl ? candid_some(value.referenceSheetUrl) : candid_none(),
        whatYouWantMade: value.whatYouWantMade,
        email: value.email,
        budgetRange: value.budgetRange,
        fursonaName: value.fursonaName
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
